server:
  port: 8804
spring:
  application:
    name: em-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: path_route
          uri: http://localhost:8804
          predicates:
            - Path=/spring_cloud/**
        - id: baidu
          uri: https://www.baidu.com
          predicates:
            - Path=/baidu/**
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true     #访问路径可以显示IP地址
    ip-address: 127.0.0.1
    non-secure-port: 8804
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8801/eureka/
zuul:
  routes:
    baidu:
      path: /baidu/**
      url: http://www.baidu.com