spring:
  application:
    name: em-eureka
  security:
    user:
      name: admin
      password: admin
server:
  port: 8801
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8801/eureka
    register-with-eureka: false
    fetch-registry: false
  server:
    # 关闭自我保护模式
    enable-self-preservation: false
    # 默认 60000 毫秒
    eviction-interval-timer-in-ms: 5000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always